# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [7]:
import numpy as np

#Assignment 1
##Q1 Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
arr = np.random.randint(1, 21, size=(5, 5))
arr[:, 2] = 1
print("Q1\n",arr)

##Q2 Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2 = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(arr2, 0)
print("\nQ2\n",arr2)

Q1
 [[14  5  1  6  6]
 [10 15  1 18  2]
 [ 9 11  1 17  2]
 [15  9  1  3 18]
 [ 5 13  1 15 13]]

Q2
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [10]:
## Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr3 = np.arange(1, 37).reshape(6, 6)
sub_arr = arr3[2:5, 1:4]
print("Q1\n", sub_arr)

#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr4 = np.random.randint(1, 21, size=(5, 5))
border_elements = np.concatenate([
    arr4[0, :],           # top row
    arr4[-1, :],          # bottom row
    arr4[1:-1, 0],        # left column (excluding corners)
    arr4[1:-1, -1]        # right column (excluding corners)
])
print("Q2\n", border_elements)

Q1
 [[14 15 16]
 [20 21 22]
 [26 27 28]]
Q2
 [19  3  3  2  1  8 17 14 15  2 14 14  3  6 10  7]


In [16]:
## Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
arr_a = np.random.randint(1, 21, size=(3, 4))
arr_b = np.random.randint(1, 21, size=(3, 4))

add = arr_a + arr_b
sub = arr_a - arr_b
mul = arr_a * arr_b
div = arr_a / arr_b

print("Q1  Array A:\n", arr_a)
print("Array B:\n", arr_b)
print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)
print("Division:\n", div)

#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr5 = np.arange(1, 17).reshape(4, 4)
row_sum = arr5.sum(axis=1)
col_sum = arr5.sum(axis=0)
print("\nQ2  Row-wise sum:\n", row_sum)
print("Column-wise sum:\n", col_sum)

Q1  Array A:
 [[11 10 12  9]
 [ 4 14 12  5]
 [ 5 13 15  1]]
Array B:
 [[10 11 20  5]
 [ 9  1  1 18]
 [11 13 11 11]]
Addition:
 [[21 21 32 14]
 [13 15 13 23]
 [16 26 26 12]]
Subtraction:
 [[  1  -1  -8   4]
 [ -5  13  11 -13]
 [ -6   0   4 -10]]
Multiplication:
 [[110 110 240  45]
 [ 36  14  12  90]
 [ 55 169 165  11]]
Division:
 [[ 1.1         0.90909091  0.6         1.8       ]
 [ 0.44444444 14.         12.          0.27777778]
 [ 0.45454545  1.          1.36363636  0.09090909]]

Q2  Row-wise sum:
 [10 26 42 58]
Column-wise sum:
 [28 32 36 40]


In [18]:
### Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr6 = np.random.randint(1, 21, size=(5, 5))
mean = np.mean(arr6)
median = np.median(arr6)
std = np.std(arr6)
var = np.var(arr6)
print("Q1\nArray:\n", arr6)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std)
print("Variance:", var)

#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr7 = np.arange(1, 10).reshape(3, 3)
mean7 = np.mean(arr7)
std7 = np.std(arr7)
normalized_arr7 = (arr7 - mean7) / std7
print("\nQ2\nOriginal Array:\n", arr7)
print("Normalized Array:\n", normalized_arr7)

Q1
Array:
 [[ 6 13  5 19  2]
 [17 19 18  4  7]
 [13 11 16 19 13]
 [ 2 18  7 13 11]
 [12 20 13 13  8]]
Mean: 11.96
Median: 13.0
Standard Deviation: 5.466113793180673
Variance: 29.878400000000003

Q2
Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [19]:
## Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr8 = np.random.randint(1, 21, size=(3, 3))
row_add = np.random.randint(1, 21, size=(3,))
result1 = arr8 + row_add
print("Q1\nArray:\n", arr8)
print("1D Array to Add:\n", row_add)
print("Result:\n", result1)

#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr9 = np.random.randint(1, 21, size=(4, 4))
col_sub = np.random.randint(1, 21, size=(4,))
result2 = arr9 - col_sub
print("Q2\nArray:\n", arr9)
print("1D Array to Subtract:\n", col_sub)
print("Result:\n", result2)

Q1
Array:
 [[ 5  5  2]
 [10 18 14]
 [ 4  1 14]]
1D Array to Add:
 [12  1 12]
Result:
 [[17  6 14]
 [22 19 26]
 [16  2 26]]
Q2
Array:
 [[ 1  4  9 12]
 [17 15  6  4]
 [14 17 15 16]
 [ 8  7  8  8]]
1D Array to Subtract:
 [ 8 20  4  8]
Result:
 [[ -7 -16   5   4]
 [  9  -5   2  -4]
 [  6  -3  11   8]
 [  0 -13   4   0]]
